config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :teams, only: %i[index show] do
    collection do
      get 'search'
    end
    resources :divisions, only: [:show], shallow: true do
      resources :members, only: [:show], shallow: true
    end
  end
  namespace :admin do
    resources :teams, only: %i[new edit create update destroy] do
      resources :divisions, only: %i[new edit create update destroy], shallow: true do
        resources :members, only: %i[new edit create update destroy], shallow: true
      end
    end
    resources :tags, only: %i[new edit create update destroy]
  end

  resources :tags, only: %i[index show] do
    collection do
      get 'search'
    end
  end

  root to: 'home#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :team
  has_many :members
  has_one_attached :image

  has_many :divisions_tags, dependent: :destroy
  has_many :tags, through: :divisions_tags

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/divisions_controller.rb
class Admin::DivisionsController < DivisionsController
  before_action :user_admin?
  def new
    @team = Team.find(params[:team_id])
    @division = Division.new
  end

  def create
    team = Team.find(params[:team_id])
    @division = team.divisions.create(division_params)

    if @division.save!
      redirect_to teams_path, success: '登録しました。'
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end

  def edit
    @division = Division.find(params[:id])
  end

  def update
    @division = Division.find(params[:id])

    if @division.update(division_params)
      redirect_to division_path, success: '更新しました。'
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @division = Division.find(params[:id])

    @division.destroy!
    redirect_to teams_path, success: '削除しました。'
  end

  private

  def division_params
    params.require(:division).permit(:name, :description, :image, :team_id, tag_ids: [])
  end

  def user_admin?
    redirect_to root_path unless current_user&.admin?
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  def show
    @division = Division.find(params[:id])
  end
end

app/views/divisions/_form.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 col-12">
      <%= form_with model: [team, division], local: true do |f| %>
        <%= render 'shared/error_messages', object: division%>
          <div class="mb-3">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class:"form-control" %>
          </div>

          <div class="mb-3">
            <%= f.label :description %>
            <%= f.text_area :description, class:"form-control" %>
          </div>

          <div class="mb-3">
            <%= f.file_field :image, class:"form-control"%>
          </div>
          
          <div class="mb-3">
            <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :title,include_hidden: false) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %>
          </div>

          <div class="actions">
            <%= f.submit class:"btn btn-primary my-2" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/divisions/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-sm-8 offset-sm-2 col-12">
      <div>
        <% breadcrumb :division, @division %>
      </div>
      <div class="card mb-3 border-0">
        <div class="row g-0">
          <div class="col-md-5">
            <% if @division.image.attached? %>
              <div class="rounded-3 team-img h-100" style="background-image: url('<%=  rails_blob_path(@division.image) %>')"></div>
            <% end %>
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <div class="card-title">
                <div>Name</div>
                <div class="text-name"><%= @division.name%></div>
              </div>
              <div>
                <% @division.tags.each do |tag| %>
                  <%= link_to tag.title, tag_path(tag), class:"badge rounded-pill bg-success" %>
                <% end %>
              </div>
              <div class="card-text border-top pt-3 mt-3">
                <div class="mb-2">
                  <%= Division.human_attribute_name(:description) %>
                </div>
                <%= @division.description %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <p class="headline-large mt-4">MEMBER</p>
      <div class="row mt-4">
        <% if @division.members.present? %>
          <% @division.members.each do |member| %>
            <div class="col-6 col-md-3">
              <%= link_to member_path(member), class:"card mb-4 text-decoration-none border-0 " do %>
                <% render partial: "shared/members", locals:{member: member}%>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div>
        <% if current_user&.admin? %>
          <%= link_to "部門削除", admin_division_path(@division), method: :delete %>
          <%= link_to "部門編集", edit_admin_division_path(@division) %>
          <%= link_to "メンバー新規登録", new_admin_division_member_path(@division) %>
        <% end %>
      </div>
    </div>
  </div>
</div>