config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :teams, only: %i[index show] do
    collection do
      get 'search'
    end
    resources :divisions, only: [:show], shallow: true do
      resources :members, only: [:show], shallow: true
    end
  end
  namespace :admin do
    resources :teams, only: %i[new edit create update destroy] do
      resources :divisions, only: %i[new edit create update destroy], shallow: true do
        resources :members, only: %i[new edit create update destroy], shallow: true
      end
    end
    resources :tags, only: %i[new edit create update destroy]
  end

  resources :tags, only: %i[index show] do
    collection do
      get 'search'
    end
  end

  root to: 'home#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :team
  has_many :members
  has_one_attached :image

  has_many :divisions_tags, dependent: :destroy
  has_many :tags, through: :divisions_tags

  validates :name, presence: true, uniqueness: true
end

app/models/divisions_tag.rb
class DivisionsTag < ApplicationRecord
  belongs_to :division
  belongs_to :tag
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :division
  has_one_attached :image

  has_many :members_tags, dependent: :destroy
  has_many :tags, through: :members_tags

  validates :name, presence: true, uniqueness: true
end

app/models/members_tag.rb
class MembersTag < ApplicationRecord
  belongs_to :member
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :divisions_tags, dependent: :destroy
  has_many :divisions, through: :divisions_tags

  has_many :members_tags, dependent: :destroy
  has_many :members, through: :members_tags

  validates :title, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_one_attached :image
  has_many :divisions, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum roll: { general: 0, admin: 1 }
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < MembersController
  before_action :user_admin?
  def new
    @division = Division.find(params[:division_id])
    @member = Member.new
  end

  def create
    @division = Division.find(params[:division_id])
    @member = @division.members.new(member_params)

    if @member.save
      redirect_to member_path(@member), success: '登録しました。'
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])

    if @member.update(member_params)
      redirect_to member_path, success: '更新しました。'
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @member = Member.find(params[:id])

    @member.destroy!
    redirect_to teams_path, success: '削除しました。'
  end

  private

  def member_params
    params.require(:member).permit(:name, :url, :biography, :image, tag_ids: [])
  end

  def user_admin?
    redirect_to root_path unless current_user&.admin?
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :user_admin?

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to teams_path, success: '登録しました。'
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)
      redirect_to teams_path, success: '更新しました。'
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])

    @tag.destroy!
    redirect_to teams_path, danger: '削除しました。'
  end

  private

  def tag_params
    params.require(:tag).permit(:title)
  end

  def user_admin?
    redirect_to root_path unless current_user&.admin?
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < TeamsController
  include Pagy::Backend
  before_action :user_admin?

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to teams_path, success: '登録しました。'
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to team_path, success: '更新しました。'
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @team = Team.find(params[:id])

    @team.destroy!
    redirect_to teams_path, success: '削除しました。'
  end

  private

  def team_params
    params.require(:team).permit(:name, :about, :image)
  end

  def user_admin?
    redirect_to root_path unless current_user&.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :set_search

  class Forbidden < ActionController::ActionControllerError; end

  class IpAddressRejected < ActionController::ActionControllerError; end

  include ErrorHandlers if Rails.env.production?

  private

  def set_search
    @search_form = SearchForm.new
  end
end

app/controllers/concerns/error_handlers.rb
module ErrorHandlers
  extend ActiveSupport::Concern

  included do
    rescue_from StandardError, with: :rescue500
    rescue_from ApplicationController::Forbidden, with: :rescue403
    rescue_from ApplicationController::IpAddressRejected, with: :rescue403
    rescue_from ActiveRecord::RecordNotFound, with: :rescue404

    private

    def rescue403(e)
      @exception = e
      render 'errors/forbidden', status: 403
    end

    def rescue404(_e)
      render 'errors/not_found', status: 404
    end

    def rescue500(_e)
      render 'errors/internal_server_error', status: 500
    end
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  def show
    @division = Division.find(params[:id])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def unprocessable_entity
    render status: 422
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @search_form = SearchForm.new(params[:search])
    @teams = @search_form.search
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @member = Member.find(params[:id])
    @division = @member.division
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include Pagy::Backend
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @dpagy, @divisions = pagy(@tag.divisions, page_param: :dpage, items: 8)
    @mpagy, @members = pagy(@tag.members, page_param: :mpage, items: 8)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  include Pagy::Backend
  def index
    @pagy, @teams = pagy(Team.all, items: 6)
    @search_form = SearchForm.new
  end

  def search
    @search_form = SearchForm.new(search_params)
    @pagy, @result = pagy(@search_form.search, items: 6)
  end

  def show
    @team = Team.find(params[:id])
  end

  private

  def search_params
    params.require(:search_form).permit(:name, :choice)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EsportsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body class="">
    <% if user_signed_in?%>
      <%= render "shared/header" %>
    <% else %>
      <%= render "shared/before_login_header" %>
    <% end %>
    <%= render "shared/flash" %>
    <div class="py-5 bg-normal" style="background-image: url('/images/mv_<%= "#{Random.new.rand(1..3)}" %>.jpg')"></div>
    <div class="container my-5">
      <%= breadcrumbs separator: " &rsaquo; " %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-3 sticky-top bg-white">
  <div class="container-fluid">
    <%= link_to "esports", root_path, class:"navbar-brand fw-bolder" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ">
        <%= link_to "チーム一覧", teams_path, class:"nav-link fw-bolder" %>
        <%= link_to "サインイン", new_user_session_path, class:"nav-link fw-bolder" %>
      </div>
    </div>
    <%= form_with model: @search_form, url: search_teams_path, method: :get, class:"d-flex" do |f| %>
      <%= f.select 'choice', [ ["チーム名","team"], ["メンバー名","member"]] %>
      <%= f.text_field :name,class:"form-control ms-1" %>
      <%= f.submit "検索" ,class:"btn btn-outline-success"%>
    <% end %>
  </div>
</nav>

app/views/shared/_divisions.html.erb
<% if division.image.attached? %>
  <div class="rounded-circle team-img" style="background-image: url('<%=  rails_blob_path(division.image) %>')"></div>
<% else %>
  <div class="rounded-circle team-img" style="background-image: url('/images/no_image.gif')"></div>
<% end %>
<div class="card-body">
  <p class="card-text"><%= division.name %></p>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="p-5 border-top">
    <div class="row">
      <div class="col-6 col-lg-3">
        <p class=" mb-2">〇〇</p>
        <ul class="p-0 list-unstyled">
          <li>
            <%= link_to "お問い合わせ", "#"%>
          </li>
        </ul>
      </div>

      <div class="col-6 col-lg-3">
        <p class=" mb-2">〇〇</p>
        <ul class="p-0 list-unstyled">
          <li>
            <%= link_to "お問い合わせ", "#"%>
          </li>
        </ul>
      </div>
      <div class="col-6 col-lg-3">
        <p class=" mb-2">その他</p>
        <ul class="p-0 list-unstyled">
          <li>
            <%= link_to "お問い合わせ", "#"%>
          </li>
          <li>
            <%= link_to "お問い合わせ", "#"%>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="bg-dark border-top">
    <div class="py-3">
      <div class="container">
        <div class="row">
          <div class="col">
            <p class="m-0 text-white">© <%= Time.now.year %> esports</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-3 sticky-top bg-white">
  <div class="container-fluid">
    <%= link_to "esports", root_path, class:"navbar-brand fw-bolder" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ">
        <%= link_to "チーム一覧", teams_path, class:"nav-link fw-bolder" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link fw-bolder" %> 
      </div>
    </div>
    <%= form_with model: @search_form, url: search_teams_path, method: :get, class:"d-flex" do |f| %>
      <%= f.select 'choice', [ ["チーム名","team"], ["メンバー名","member"]] %>
      <%= f.text_field :name,class:"form-control ms-1" %>
      <%= f.submit "検索" ,class:"btn btn-outline-success"%>
    <% end %>
  </div>
</nav>

app/views/shared/_members.html.erb
<% if member.image.attached? %>
  <div class="rounded-circle team-img" style="background-image: url('<%=  rails_blob_path(member.image) %>')"></div>
<% else %>
  <div class="rounded-circle team-img" style="background-image: url('/images/no_image.gif')"></div>
<% end %>
<div class="card-body">
  <p class="card-text"><%= member.name %></p>
</div>