config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :teams, only: %i[index show] do
    collection do
      get 'search'
    end
    resources :divisions, only: [:show], shallow: true do
      resources :members, only: [:show], shallow: true
    end
  end
  namespace :admin do
    resources :teams, only: %i[new edit create update destroy] do
      resources :divisions, only: %i[new edit create update destroy], shallow: true do
        resources :members, only: %i[new edit create update destroy], shallow: true
      end
    end
    resources :tags, only: %i[new edit create update destroy]
  end

  resources :tags, only: %i[index show] do
    collection do
      get 'search'
    end
  end

  root to: 'home#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :divisions_tags, dependent: :destroy
  has_many :divisions, through: :divisions_tags

  has_many :members_tags, dependent: :destroy
  has_many :members, through: :members_tags

  validates :title, presence: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :user_admin?

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to teams_path, success: '登録しました。'
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)
      redirect_to teams_path, success: '更新しました。'
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])

    @tag.destroy!
    redirect_to teams_path, danger: '削除しました。'
  end

  private

  def tag_params
    params.require(:tag).permit(:title)
  end

  def user_admin?
    redirect_to root_path unless current_user&.admin?
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include Pagy::Backend
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @dpagy, @divisions = pagy(@tag.divisions, page_param: :dpage, items: 8)
    @mpagy, @members = pagy(@tag.members, page_param: :mpage, items: 8)
  end
end

app/views/tags/_form.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 col-12">
      <%= form_with model: [tag], local: true do |f| %>
        <%= render 'shared/error_messages', object: tag %>
          <div class="mb-3">
            <%= f.label :title %>
            <%= f.text_field :title, autofocus: true, class:"form-control" %>
          </div>

          <div class="actions">
            <%= f.submit class:"btn btn-primary my-2" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/index.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-12">
      <% @tags.each do |tag| %>
        <ul class="list-unstyled">
          <li>
            <%= tag.title %>
            <%= link_to "編集", edit_tag_path(tag), class:"btn btn-primary" %>
            <%= link_to "削除", tag_path(tag), class:"btn btn-primary", method: :delete %>
          </li>
        </ul>
        <% end %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<h3 class="headline-large mt-4">タグ：<%= @tag.title %>関連</h3>
<div class="container my-5">
  <div class="col-sm-8 offset-sm-2 col-12">
    <p class="headline-large mt-4">division</p>
    <div class="row mt-4">
      <% if @divisions.present? %>
        <% @divisions.each do |division| %>
          <div class="col-6 col-md-3">
            <%= link_to division_path(division), class:"card mb-4 text-decoration-none border-0 " do %>
              <% render partial: "shared/divisions", locals: {division: division} %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <div class="m-3 d-flex justify-content-center">
        <%== pagy_bootstrap_nav(@dpagy) %>
      </div>
    </div>
    <p class="headline-large mt-4">MEMBER</p>
    <div class="row mt-4">
      <% if @members.present? %>
        <% @members.each do |member| %>
          <div class="col-6 col-md-3">
            <%= link_to member_path(member), class:"card mb-4 text-decoration-none border-0 " do %>
              <% render partial: "shared/members", locals:{member: member}%>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <div class="m-3 d-flex justify-content-center">
        <%== pagy_bootstrap_nav(@mpagy) %>
      </div>
    </div>
  </div>
  <div>
    <%= link_to "編集", edit_admin_tag_path %>
    <%= link_to "削除", admin_tag_path, method: :delete %>
  </div>
</div>