config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :teams, only: %i[index show] do
    collection do
      get 'search'
    end
    resources :divisions, only: [:show], shallow: true do
      resources :members, only: [:show], shallow: true
    end
  end
  namespace :admin do
    resources :teams, only: %i[new edit create update destroy] do
      resources :divisions, only: %i[new edit create update destroy], shallow: true do
        resources :members, only: %i[new edit create update destroy], shallow: true
      end
    end
    resources :tags, only: %i[new edit create update destroy]
  end

  resources :tags, only: %i[index show] do
    collection do
      get 'search'
    end
  end

  root to: 'home#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :division
  has_one_attached :image

  has_many :members_tags, dependent: :destroy
  has_many :tags, through: :members_tags

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < MembersController
  before_action :user_admin?
  def new
    @division = Division.find(params[:division_id])
    @member = Member.new
  end

  def create
    @division = Division.find(params[:division_id])
    @member = @division.members.new(member_params)

    if @member.save
      redirect_to member_path(@member), success: '登録しました。'
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])

    if @member.update(member_params)
      redirect_to member_path, success: '更新しました。'
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @member = Member.find(params[:id])

    @member.destroy!
    redirect_to teams_path, success: '削除しました。'
  end

  private

  def member_params
    params.require(:member).permit(:name, :url, :biography, :image, tag_ids: [])
  end

  def user_admin?
    redirect_to root_path unless current_user&.admin?
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @member = Member.find(params[:id])
    @division = @member.division
  end
end

app/views/members/_form.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 col-12">
      <%= form_with model: [division, member], local: true do |f| %>
        <%= render 'shared/error_messages', object: member %>
          <div>
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, class:"form-control" %>
          </div>

          <div>
            <%= f.label :url %>
            <%= f.text_area :url, class:"form-control" %>
          </div>

          <div>
            <%= f.label :biography %>
            <%= f.text_area :biography, class:"form-control" %>
          </div>

          <div class="field">
            <%= f.file_field :image, class:"form-control"%>
          </div>

          <div class="mb-3">
            <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :title,include_hidden: false) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %>
          </div>

          <div class="actions">
            <%= f.submit class:"btn btn-primary my-2" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/members/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-sm-8 offset-sm-2 col-12">
      <div>
        <% breadcrumb :member, @member %>
      </div>
      <div class="card mb-3 border-0">
        <div class="row g-0">
          <div class="col-md-4">
            <% if @member.image.attached? %>
              <div class="rounded-3 team-img h-100" style="background-image: url('<%=  rails_blob_path(@member.image) %>')"></div>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <div class="card-title">
                <div>Name</div>
                <div class="text-name"><%= @member.name%></div>
              </div>
              <div class="card-text">　
                <% if @member.url.present?%>
                  <%= link_to @member.url do %>
                    <i class="fab fa-twitter fa-lg text-black"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="card-text border-top pt-3 mt-3">
                <div class="mb-2">
                  <%= Member.human_attribute_name(:biography) %>
                </div>
                <%= @member.biography%>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if current_user&.admin? %>
        <%= link_to "メンバー編集" , edit_admin_member_path(@member) %>
        <%= link_to "メンバー削除" , admin_member_path(@member), method: :delete %>
      <% end %>
    </div>
  </div>
</div>